#!/usr/bin/groovy

// load pipeline functions
// Requires pipeline-github-lib plugin to load library from github

// For testing: set to a specific commit hash
@Library('github.com/Mellanox/ci-demo@stable_media')
def matrix = new com.mellanox.cicd.Matrix()

matrix.main()
